apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "example-app"
  labels:
    app.kubernetes.io/name: "example-app"
spec:
  descriptor:
    links:
      - description: 'Open Example Application'
        # a clever (read: hacked) way to hide the button for Embedded clusters
        url: '{{repl if (not (IsKurl)) }}http://example-nginx{{repl end}}'
